### ISSUE TITLE
Review and update developer documentation

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1698]
Our `/docs/` folder has lots of developer documentation. It hasn't been holistically reviewed in a while. Having good documentation will be important for transition.

- [x] api.md - #1703 
- [x] auth.md - #1733
- [x] changelog.md
- [ ] deploy.md - #1795
- [x] docker.md - #1904
- [x] email.md
- [ ] environment.md - #1902, maybe
- [x] frontend.md - #1903
- [x] index.rst
- [ ] monitoring.md - #1913
- [ ] release.md - #1795
- [x] ~~selenium.md~~ This file was destroyed as part of the Great Selenium Cleansing of #1767.
- [ ] setup.md - #1901
- [x] testing.md
- [x] ~~updating_data.md~~ This file has been removed and largely replaced by the ultra-awesome admin help in #1844.

**Comment by jseppi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a CALC developer, I need to review the developer docs to ensure they are up to date and to identify additional documentation tasks for transitioning CALC.](https://trello.com/c/SD64mBiL/252-as-a-calc-developer-i-need-to-review-the-developer-docs-to-ensure-they-are-up-to-date-and-to-identify-additional-documentation-t)

**Comment by jseppi** [comment]
related: #840

**Comment by toolness** [comment]
**Update:** we've now got DRF-generated API documentation (and interactivity) done in #1797 but more work needs to be done on actually connecting it with (or using it to completely replace) `docs/api.md`.  I've filed #1802 to address that.

**Comment by toolness** [comment]
Ok, at this point all the remaining items have been spun off into separate PRs, so I'm closing this issue.
