### ISSUE TITLE
General improvements to API documentation

### ISSUE THREAD

**Issue by toolness** [18F/calc#1802]
After landing #1797 we've got snazzy interactive API docs at https://calc-dev.app.cloud.gov/api/docs/, but there are a bunch of other things we can do to improve our API documentation:

- [X] Consider ~~mounting these docs at~~ redirecting `/api/` ~~instead of~~ to `/api/docs/`.  Currently `/api/` just 404s, and it's more easy to type and find that way. (Done in #1811.)
- [X] Link to `/api/docs/` from the Sphinx docs at https://calc-dev.app.cloud.gov/docs/. (Done in #1811.)
- [X] Consider making the docs a bit more robust. Right now they're fairly minimal and some fields are a bit vague (e.g. worksite). (Done in #1811.)
- [X] Consider either merging the existing [`API.md`](https://calc-dev.app.cloud.gov/docs/api.html) into these API docs or getting rid of them entirely. (Done in #1811.)
- [X] It'd be nice if these API docs were linked-to from (or even embedded in) the actual HTML views of the API endpoints.  So that e.g. if someone went to [`/api/rates/`](https://calc-dev.app.cloud.gov/api/rates/) with their browser, aside from seeing the HTML-rendered version of the response, they'd also see a link to `/api/docs/` or something.  (Done in #1811.)
