### ISSUE TITLE
A simple running checklist of style guide contents

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1851]
## A simple running checklist of style guide contents (v0.1)

Check off items as they are added. Let's not worry about whether the style (or description) of a specific element needs to be updated. That comes next. For this sprint, the task is to make sure everything is simply **there** (and then to make whatever updates time allows).

 - [x] < Signifies "created." May not yet be merged into `develop`

- [x] Welcome
  - [x] General intro (welcome, external asset links, statement re progressive enhancement)
  - [x] ~About our design (this and above will occupy a single page)~ Current intro plus accessibility notes may suffice for v1
  - [x] Accessibility

### Basics
- [ ] Typography
   - [x] Simple wysiwig list of header and text formats
   - [ ] Text link styles (#1950)
- [x] Colors
  - [x] Palette
  - [x] Accessibility ~grid~ notations
  - [x] Recommended color combinations
- [ ] Layout grid
- [x] Focus states (@hbillings working on these)
  - [x] Over light backgrounds
  - [x] Over dark backgrounds
- [x] Compatibility mode

### Components
- [x] Header and primary navigation
- [x] Footer
- [ ] User options menu
- [x] Card layout (our basic content grid, with width variations)
- [ ] Buttons
  - [x] Default (primary)
  - [ ] ~Primary: link~
  - [x] Primary: input
  - [x] Primary: submit
  - [x] Outlined
  - [x] Disabled
  - [x] Secondary
  - [ ] White (footer login)
  - [ ] ~Gray~
  - [x] Text
- [x] Alerts
  - [x] Error
  - [x] Success
  - [x] Warning
  - [x] Info
- [ ] Status [labels](https://github.com/18F/calc/issues/1149)
- [ ] Tool tips
  - [x] Errors (e.g. for tables)
  - [ ] Info (e.g. on home-page filter panel)
- [ ] Tables
  - [x] Data table
  - [ ] Sortable table
  - [x] Excel tables (for examples)

### Forms
- [x] Ajax form and upload widget (interactive form elements, with notes on accessibility and graceful degredation)
- [ ] Text input
  - [x] Labeled
  - [x] Labeled, with focus (doesn't show focus unless you click, so it looks / acts the same as the above)
  - [ ] Labeled, with help caption
  - [x] Input error
- [x] Text area
- [x] Checkboxes
- [x] Radio buttons
- [x] Date widget
- [x] Selector
- [x] Uploader
- [x] Expandable area (accordion)
- [x] Form button row
- [x] Modal dialog
- [ ] Steps widget
  - [x] Static example
  - [ ] Interactive

### Templates
- [x] Email templates
  - [x] Price list approved
  - [x] Price list retired
  - [x] Price list rejected
  - [x] Bulk upload succeeded (covers single uploads, too?)
  - [x] Bulk upload failed (covers single uploads, too?)
  - [x] Approval reminder

### Other
- [ ] [Disable form validation](https://github.com/18F/calc/issues/568) (@toolness?)

_**more to come**_

**Comment by ericronne** [comment]
Issues created for the non-moot outstanding items
