### ISSUE TITLE
Finish these tasks so we can push to prod!

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1962]
It's been a long time since we've published a new version of the site, and many CALC changes and improvements are champing at the bit to go live. We're in the home stretch! Let's check off the necessary tasks below, and then proceed with the ceremonies.

_**Please add to this list, modify or ask questions about my listing logic, and check off items as they are completed. Thanks!**_

### PRs to close
- [x] Fixes for buttons #1955
- [x] Improve our button set #1916
- [x] Er home bg colorfix and blue add #1961 
- [x] Apply usa-sr-classes everywhere #1958 
- [x] Give the data explorer table more room to breathe #1963
- [ ] ~[WIP] Remove staging tier of deployments #1795~ (wait a few days on this)

### PRs which should explicitly _not_ be merged for this release
- Unless otherwise indicated, anything marked [WIP]
- Implement step indicator styles #1819 
- Adds login functionality to header #1701 
- Sort autocomplete suggestions by length #1717 

### QA once-over (after all of the above boxes have been checked)
- [x] @ericronne
- [ ] @toolness 
- [x] @hbillings 
- [ ] @tram 
- [ ] @KellyBailey

**Comment by ericronne** [comment]
How do people feel about a **Wednesday** push to live, in order to give us enough time to QA?

Lots of changes here.

Feel free to emoji vote:
👍= Wednesday
👎= Git 'er done by Tuesday

**Comment by tram** [comment]
Maybe take a look at this again Wednesday for a Wednesday or Thursday push? (@ericronne & @toolness are both out.)

**Comment by hbillings** [comment]
@tram If we can get #1764 merged, you and I can QA today, and then @ericronne and @toolness will be set to QA Wednesday morning for a possible Wednesday afternoon push. Does that sound reasonable?

**Comment by hbillings** [comment]
I've taken a spin through the site and noted #1967, #1968, and #1970. I don't feel like any of them are dealbreakers (though #1970 feels like it really should be fixed if I can get to it).

**Comment by ericronne** [comment]
🎉 !
